import25=["Acouth Deng",
"Ahmad Gilbert",
"Austin Waverly",
"Banyard Nick",
"Byron Byron",
"Byron Mullens",
"Byron Wesley",
"Devon Scott",
"Hammonds Marcus",
"Hardy Tae",
"Harris Anthony",
"Jeantal Cylla",
"Jhonson Orlando",
"Joshia Gray",
"Kris Clyburn",
"Maxie Kunle Esho",
"McKenzie Moore",
"Moss Justin",
"Petteway Terran",
"Shamorie S Ponds",
"Stephen Stephen",
"Stone Diamond",
"Thomas Lance",
"Thomes Elijah",
"Tolbert Jordan",
"Tripp Jahlil",
"Tyrrel Joseph Alexis Tate",
"Walker Kyree",
"Waverly Austin",
"Williams Pendarvis",
"Wooten JR Kenneth",

"Amarah Coleman",
"Dominique Leonidas",
"Taylor Lynn Hosendove",
"Grace Berg",
"Lindsey Denise Pulliam",
"Gabrielle Gonzalez",
"King Kristina",
"Michaela Lynn Porter"


"A.Williams George",
"Alexander Mitrovic",
"Amarah Coleman",
"Amber Keith",
"Blake Christopher",
"Brian Bridgeford",
"Britney Jones",
"Delph Ronald",
"Dominique Leonidas",
"Durrell La Faunce Summers",
"Hamilton Kendarrius",
"Hammonds Marcus",
"Harris Anthony",
"Harris Ramon",
"Jarron Crump",
"King Kristina",
"Maitland Malik",
"Malcolm Jaleel Rhett",
"Marco Gryzak",
"Moore Doral",
"O'Brien Todd",
"Rashida Timbilla",
"Stanford Jr William",
"Stone Diamond",
"Troy Baxter",
"Wooten Jr Steve",
"Geraldynn Leaupepe",
"Jones Lish Frederick"
]
link25_post=[ "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637114/", #HYL vs DAR g3
              "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637115/", #BCG vs SEL g3
               "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637116/ ", #SGA vs ETM g4
              "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637118/bs.html",  #ZAV vs BM game 4
               
            ]
links_25_season=["https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2626122/bs.html",  #HYL vs AMZ game5
                 "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2592020/bs.html",# zav vs Sel
                 "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2592019/"  #SGA vs ETM
                 ]
post2025=[ 
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637102", # BM vs BRO game1
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637103", #SGA vs ETM game1
         "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637104", #HYL vs DAR game1
          "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637106/", # BCH vs SEL game1


          "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637107/bs.html", # ETM vs SGA game2
         " https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637111/", #DAR vs HYL game2
          " https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637109/", # SEL vs BCH game2
          "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637108/", # BM vs BRO game2
          
          "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637112/",  #BM vs BRO game3
          "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2637113/"  #SGA vs ETM game3
         ]
links_24_season =["https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376889/", 
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376890/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376891/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376892/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376893/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376894/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376895/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376896/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376898/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376921/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376922/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376927/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376926/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376931/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376936/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376937/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376939/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376940/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376942/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376944/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376945/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376948/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376950/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376951/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376952/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376954/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376953/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376956/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376959/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376960/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376962/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376963/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376965/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376968/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376967/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376969/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376972/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376973/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376975/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376976/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376977/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376978/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376979/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376980/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376981/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376983/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376982/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376984/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376985/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376986/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376987/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376988/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376989/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376990/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376992/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376993/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376995/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376994/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376996/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376997/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376998/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2388292/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377000/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377001/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377002/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377003/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377004/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377005/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377006/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2377007/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386150/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386151/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386152/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386153/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386154/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386155/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386156/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386157/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386158/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386159/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386161/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386160/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386162/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386163/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386164/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386165/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386166/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386168/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386167/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386169/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386170/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386171/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386172/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386173/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386174/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386175/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386176/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386177/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386178/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386179/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386180/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386181/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386182/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386183/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386184/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386185/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386186/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386187/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386188/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386189/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386190/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386191/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386192/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386193/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386194/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386195/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386196/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386197/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386198/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386202/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386203/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386204/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400818/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386206/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386207/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386208/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386209/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386210/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386211/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386212/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386213/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2402067/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386215/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386216/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386217/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386218/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386219/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386220/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386221/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386222/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386223/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386224/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2403563/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386226/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386227/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386228/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386229/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386230/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386231/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386232/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386233/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386234/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386235/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386236/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386237/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386238/" ]
links_24_sea_fem=[
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376864/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376865/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376866/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376867/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376868/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376869/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376871/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376872/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376873/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376874/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376878/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376879/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376880/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376881/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376882/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2376883/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386124/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386125/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386126/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386127/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386128/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386129/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386130/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386131/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386132/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386133/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386134/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386135/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386136/",
           "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2386137/" ]

links24_male_post=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405272/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405275/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405277/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405278/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405279/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405280/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405281/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405282/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405287/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405288/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405292/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405295/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405296/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405297/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405298/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405299/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408009/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408010/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408011/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408012/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408013/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408975/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408976/",

            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408952/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408953/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409749/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2410798/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2417636/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2417638/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2422333/",

            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409745/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409750/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2417634/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2417635/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2417637/",



            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2423905/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2423914/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2423915/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2423918/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2427005/"
]
links24_female_post=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400819/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400827/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400830/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400831/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400832/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400833/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400834/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2400838/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405249/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2405250/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2406742/",

            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408950/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2408951/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409752/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409753/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2409754/"

]
links_23_season=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2216142/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2216141/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2218960/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2218961/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2218962/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219100/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219101/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219102/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219363/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219364/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220098/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220118/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220815/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220818/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2221790/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2221791/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222571/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222577/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222737/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222738/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223494/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223495/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223776/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223796/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224117/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224118/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224593/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224594/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224826/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224827/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2225827/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2225828/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226178/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226179/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226180/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226181/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226182/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226183/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226184/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2227226/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226186/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226187/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226188/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226189/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226190/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226191/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226195/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2228962/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226196/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226197/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226428/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226429/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226430/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226438/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2229917/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226460/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226461/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226462/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226463/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226464/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226465/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226466/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226475/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226476/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226477/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226478/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226479/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226480/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226481/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226482/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226483/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226484/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226485/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226486/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226487/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226488/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226489/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226490/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226491/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226492/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226493/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226494/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226495/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226496/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226497/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226498/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226500/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226501/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226502/",	
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226503/"	
]
links23_male_post=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2248641/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2248642/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249000/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249002/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249209/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249215/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249448/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249451/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249624/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2250572/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249657/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2250549/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251283/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251292/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251530/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251552/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251910/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2252190/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2252235/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2254147/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2255155/",

            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2256455/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2257560/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2258371/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2259168/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2257097/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2257808/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2258950/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2259375/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2263870/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2264234/",

            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2264735/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265062/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265535/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265977/"


]

links_23_sea_fem=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2216143/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2218963/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219099/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2219365/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220058/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2220811/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2221789/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222506/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2222736/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223493/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2223765/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224115/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224587/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2224821/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2225826/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226159/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226160/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226161/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226162/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226163/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226164/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226165/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226170/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226171/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226172/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226173/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226174/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226175/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226176/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2226177/"

]   

links23_female_post=[
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2248639/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2248967/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249212/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2249450/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251214/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2251476/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2254133/",


            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2264665/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265038/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265534/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2265976/",
            "https://fibalivestats.dcd.shared.geniussports.com/u/MNBA/2266719/"

]


#Lish Freddie,Anthonyс Smith,Stone Diamond ,Tripp Jahlil 
#WILLIAMS PENDARVIS,Thompson Sam,Nikola Tadic,William Stanford
#Jaylen Jowan D Bland,Summers Durrell,LaMontray Shakur Harris
#Kendarrius Hamilton,Jericole Hellems,Jeantal Cylla,Walker Kyree,Key Jaylon,Brown Brandon
#Nemanja Miliosevic,Hester Antonio,Taylor Jr Steve,Archie Kaden,Henderson Harrison,Devoe Joseph,A.Williams George,Moss Justin
#Blake Christopher,Benson Keith,Жереми Артур,Wiggins Nicholas,Harris Anthony,Terry Thomas,Summers Jarvis
#Lucas Kalin,Divine Myles